### ISSUE TITLE
Playback of sample audio shortened

### ISSUE THREAD

**Issue by besi** [miketeachman/micropython-esp32-i2s-examples#5]
I am getting sound out of my [max98357](https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/raspberry-pi-usage) DAC. However when I run the `taunt-16k-16bits-mono-12db.wav` file I get an audio signal that sounds like this:

> Now now now now now now now now now now now...

Instead of 

> Now go away, or I shall taunt you a second time... 

In the console I get some messages like this every three to four seconds:

raw REPL; CTRL-B to exit
>OK

```
E (466560) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (466560) task_wdt:  - IDLE1 (CPU 1)
E (466560) task_wdt: Tasks currently running:
E (466560) task_wdt: CPU 0: IDLE0
E (466560) task_wdt: CPU 1: mp_task
E (471560) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (471560) task_wdt:  - IDLE1 (CPU 1)
E (471560) task_wdt: Tasks currently running:
E (471560) task_wdt: CPU 0: IDLE0
E (471560) task_wdt: CPU 1: mp_task
E (476560) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (476560) task_wdt:  - IDLE1 (CPU 1)
E (476560) task_wdt: Tasks currently running:
E (476560) task_wdt: CPU 0: IDLE0
E (476560) task_wdt: CPU 1: mp_task
```

Here is what it sounds like:
https://media.vocaroo.com/mp3/1pFKFog4YhD

**Comment by miketeachman** [comment]
Hi @besi ,
thanks for the detailed description of the problem.  I can try to help you solve this.

Can you please describe your hardware and build configuration:
- ESP32 module are you using
- wiring used to connect the ESP32 to the Adafruit breakout board.  e.g.  breadboard with jumper connections, stripboard with soldered connections, or ?
- build options that might affect the driver behavior.  e.g.  single core vs dual core, others?

Yesterday, I created a new local build where I rebased the I2S PR with the latest MicroPython commits.  I flashed the binary into a Lolin D32 ESP32 module and tried the [mono example](https://github.com/miketeachman/micropython-esp32-i2s-examples/blob/master/examples/play-mono-wav.py) with an Adafruit  max98357 breakout board.  It seemed to work as expected -- the entire WAV file sample played from the speaker.

I attached this MicroPython binary in case you would like to try it.  That would help to narrow the root cause of the problem to your build versus your hardware.

[MicroPython v1.11-Nov-27-2019-with-I2S.bin.zip](https://github.com/miketeachman/micropython-esp32-i2s-examples/files/3917876/MicroPython.v1.11-Nov-27-2019-with-I2S.bin.zip)

**Comment by miketeachman** [comment]
No response from user to information request.  Assume issue is resolved.
